### ISSUE TITLE
potrace script documentation

### ISSUE THREAD

**Issue by disconsis** [fennerm/artwiz-lemon-ttf#1]
Hey, awesome work!
There's a few bitmap fonts I've always wanted to try out, that are so small they hurt my head.
I was trying to use this on them (specifically, scientifica).
However, simply `./potrace scientifica.bdf` didn't work. Looks like it needs an image (since you're using ImageMagick?!). Anyway, documentation would be a real help!

**Comment by fennerm** [comment]
I'll add some more documentation to the potrace script but I should warn you that vectorizing bitmap fonts is a pretty manual and clunky process unfortunately. Here's the basic workflow:
1. Install fontforge and potrace
2. Add my potrace script to your `$PATH` so that it is ahead of the system potrace.
3. Open the bitmap font in fontforge
4. Select all characters.
5. Autotrace all characters (this will call our custom potrace script)
6. Examine characters manually and spot correct any badly traced ones
7. Generate a ttf font.

You'll probably need to adjust the potrace parameters to your specific font.

If you're interested in this problem, I think what we really need is a more fleshed out tool for doing the conversion properly. The current process is awful.

Here's some more resources I found useful:
[http://monsterfacegames.blogspot.com/2013/10/creating-pixel-font-for-your-game.html](http://monsterfacegames.blogspot.com/2013/10/creating-pixel-font-for-your-game.html)
[https://stackoverflow.com/questions/3750124/how-to-convert-a-bitmap-font-fon-into-a-truetype-font-ttf/8350648](https://stackoverflow.com/questions/3750124/how-to-convert-a-bitmap-font-fon-into-a-truetype-font-ttf/8350648)
[https://gist.github.com/bendmorris/7170209](https://gist.github.com/bendmorris/7170209)

**Comment by fennerm** [comment]
Closing this issue but please feel free to reach out if you have any further qs

**Comment by disconsis** [comment]
Thanks for the response, and your work! Pretty sure I won't be doing this myself then for other fonts :stuck_out_tongue_winking_eye:
